/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.56
 * Generated at: 2023-03-19 06:19:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class AdminLogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("\r\n");
      out.write("  <title>AgriFood</title>\r\n");
      out.write("  <meta content=\"\" name=\"description\">\r\n");
      out.write("  <meta content=\"\" name=\"keywords\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Favicons -->\r\n");
      out.write("  <link href=\"assets/img/favicon.png\" rel=\"icon\">\r\n");
      out.write("  <link href=\"assets/img/apple-touch-icon.png\" rel=\"apple-touch-icon\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Google Fonts -->\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor CSS Files -->\r\n");
      out.write("  <link href=\"assets/vendor/aos/aos.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/vendor/bootstrap-icons/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/vendor/boxicons/css/boxicons.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/vendor/glightbox/css/glightbox.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/vendor/swiper/swiper-bundle.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Template Main CSS File -->\r\n");
      out.write("  <link href=\"assets/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- =======================================================\r\n");
      out.write("  * Template Name: Remember - v4.7.0\r\n");
      out.write("  * Template URL: https://bootstrapmade.com/remember-free-multipurpose-bootstrap-template/\r\n");
      out.write("  * Author: BootstrapMade.com\r\n");
      out.write("  * License: https://bootstrapmade.com/license/\r\n");
      out.write("  ======================================================== -->\r\n");
      out.write("<style>\r\n");
      out.write("#about{\r\n");
      out.write("\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 81.70vh;\r\n");
      out.write("/*   background: url(\"../img/hero.jpg\") top center; */\r\n");
      out.write("  background-size: cover;\r\n");
      out.write("  position: relative;\r\n");
      out.write("}\r\n");
      out.write(".midbar .search-container button {\r\n");
      out.write("  float: right;\r\n");
      out.write("  padding: 6px 10px;\r\n");
      out.write("  margin-top: 8px;\r\n");
      out.write("  margin-right: 16px;\r\n");
      out.write("  background: #ddd;\r\n");
      out.write("  font-size: 17px;\r\n");
      out.write("  border: none;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".midbar .search-container button:hover {\r\n");
      out.write("  background: #ccc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media screen and (max-width: 600px) {\r\n");
      out.write("  .midbar .search-container {\r\n");
      out.write("    float: none;\r\n");
      out.write("  }\r\n");
      out.write("  .midbar a, .midbar input[type=text], .midbar .search-container button {\r\n");
      out.write("    float: none;\r\n");
      out.write("    display: block;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 14px;\r\n");
      out.write("  }\r\n");
      out.write("  .midbar input[type=text] {\r\n");
      out.write("    border: 1px solid #ccc;  \r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* input[type=text], input[type=password] {\r\n");
      out.write("  \r\n");
      out.write("  width: 80%;\r\n");
      out.write("  padding: 10px 10px;\r\n");
      out.write("  margin: 5px 0;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  border: 1px solid #ccc;\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("  align:center;`\r\n");
      out.write("} */\r\n");
      out.write("  input[type=button], input[type=submit], input[type=reset] {\r\n");
      out.write(" \r\n");
      out.write("	/*  position:relative; */\r\n");
      out.write("    padding: 11px 32px;\r\n");
      out.write("	border-radius:15px;\r\n");
      out.write("	background-color:#4CAF50;\r\n");
      out.write("	align:center;	\r\n");
      out.write("	color: white;\r\n");
      out.write("	text-decoration: none; \r\n");
      out.write("    font-size: 17px;\r\n");
      out.write("    margin: 4px 2px;\r\n");
      out.write("    cursor: pointer; \r\n");
      out.write("}  \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  <!-- ======= Header ======= -->\r\n");
      out.write("<header id=\"header\" class=\"d-flex align-items-center\">\r\n");
      out.write("    <div class=\"container d-flex justify-content-between\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"logo\">\r\n");
      out.write("        <h1 class=\"text-light\"><a href=\"Home.jsp\">AgriFood</a></h1>\r\n");
      out.write("        <!-- Uncomment below if you prefer to use an image logo -->\r\n");
      out.write("        <!-- <a href=\"index.html\"><img src=\"assets/img/logo.png\" alt=\"\" class=\"img-fluid\"></a>-->\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <nav id=\"navbar\" class=\"navbar\">\r\n");
      out.write("        <ul>\r\n");
      out.write("        <li><a href=\"Home.jsp\">Home</a></li>\r\n");
      out.write("         \r\n");
      out.write("          <li><a href=\"UserLogin.jsp\">User</a></li> \r\n");
      out.write("          \r\n");
      out.write("          <li><a href=\"AdminLogin.jsp\">Admin</a></li>\r\n");
      out.write("      \r\n");
      out.write("        </ul>\r\n");
      out.write("        <i class=\"bi bi-list mobile-nav-toggle\"></i>\r\n");
      out.write("      </nav><!-- .navbar -->\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </header><!-- End Header -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  <!-- ======= About Section ======= -->\r\n");
      out.write("     <section id=\"aboutt\" class=\"aboutt\" style=\"background-color: #eee;\">\r\n");
      out.write("    \r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row d-flex justify-content-center align-items-center h-100\">\r\n");
      out.write("     <div class=\"col-xl-10\">\r\n");
      out.write("        <div class=\"card rounded-3 text-black\">\r\n");
      out.write("          <div class=\"row g-0\">\r\n");
      out.write("          <div class=\"col-xl-6 col-lg-6 video-box d-flex justify-content-center align-items-stretch\" data-aos=\"zoom-in\">\r\n");
      out.write("            <a href=\"https://www.youtube.com/watch?v=jDDaplaOz7Q\" class=\"venobox play-btn mb-4\" data-vbtype=\"video\" data-autoplay=\"true\"></a>\r\n");
      out.write("       <img src=\"assets/img/admin.jpg\" width=\"465px\" >\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-xl-6 col-lg-6 d-flex flex-column align-items-stretch justify-content-center py-5 px-lg-5\">\r\n");
      out.write("            <div class=\"box-heading\" data-aos=\"fade-up\">\r\n");
      out.write("              <center><h4>Log In</h4></center>\r\n");
      out.write("             <div class=\"text-center\">\r\n");
      out.write("            \r\n");
      out.write("             \r\n");
      out.write("              <form action=\"AdminLoginCon\" method=\"post\">\r\n");
      out.write("           <div class=\"form-group mt-1\">           \r\n");
      out.write("                <input type=\"text\" class=\"form-control\" name=\"email\" id=\"email\" placeholder=\"Enter Email ID.\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group mt-1\">\r\n");
      out.write("                <input type=\"password\" class=\"form-control\" name=\"pass\" id=\"pass\" placeholder=\"Enter Password\" required>\r\n");
      out.write("              </div><br>\r\n");
      out.write("               <div class=\"form-group mt-1\">                        \r\n");
      out.write("          \r\n");
      out.write("                         \r\n");
      out.write("       <input type=\"Submit\" value=\"SignIn\" class=\"about-btn\"></div>                       \r\n");
      out.write("             </form>\r\n");
      out.write("            \r\n");
      out.write("           \r\n");
      out.write("             \r\n");
      out.write("              </div>               \r\n");
      out.write("            </div>           \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div></div></div></div></div>\r\n");
      out.write("      <br><br>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("<!--  ======= Footer ======= -->\r\n");
      out.write(" <footer id=\"footer\">\r\n");
      out.write("\r\n");
      out.write("   <!--  <div class=\"footer-top\"> -->\r\n");
      out.write("       <div class=\"col-lg-6\">\r\n");
      out.write("             <div class=\"contact-info d-flex align-items-left\">\r\n");
      out.write("     <a href=\"Home.jsp\"><img src=\"assets/img/logo.png\" width=\"50px\" height=\"50px\"></a></i></div>\r\n");
      out.write("             </div>\r\n");
      out.write("  	   \r\n");
      out.write("      \r\n");
      out.write("    \r\n");
      out.write("  </footer><!-- End Footer -->\r\n");
      out.write("  <!-- Vendor JS Files -->\r\n");
      out.write("  <script src=\"assets/vendor/purecounter/purecounter.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/aos/aos.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/glightbox/js/glightbox.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/isotope-layout/isotope.pkgd.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/swiper/swiper-bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/php-email-form/validate.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Template Main JS File -->\r\n");
      out.write("  <script src=\"assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
