/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.56
 * Generated at: 2023-03-20 10:44:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import java.sql.Statement;
import com.connection.DBConnection;
import java.sql.Connection;

public final class E_002dMarket_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("com.connection.DBConnection");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("\r\n");
      out.write("  <title>AgriTech</title>\r\n");
      out.write("  <meta content=\"\" name=\"description\">\r\n");
      out.write("  <meta content=\"\" name=\"keywords\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Favicons -->\r\n");
      out.write("  <link href=\"assets/img/favicon.png\" rel=\"icon\">\r\n");
      out.write("  <link href=\"assets/img/apple-touch-icon.png\" rel=\"apple-touch-icon\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Google Fonts -->\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor CSS Files -->\r\n");
      out.write("  <link href=\"assets/vendor/aos/aos.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/vendor/bootstrap-icons/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/vendor/boxicons/css/boxicons.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/vendor/glightbox/css/glightbox.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/vendor/swiper/swiper-bundle.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Template Main CSS File -->\r\n");
      out.write("  <link href=\"assets/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- =======================================================\r\n");
      out.write("  * Template Name: Remember - v4.7.0\r\n");
      out.write("  * Template URL: https://bootstrapmade.com/remember-free-multipurpose-bootstrap-template/\r\n");
      out.write("  * Author: BootstrapMade.com\r\n");
      out.write("  * License: https://bootstrapmade.com/license/\r\n");
      out.write("  ======================================================== -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("* {\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form.example input[type=text] {\r\n");
      out.write("  padding: 5px;\r\n");
      out.write("  font-size: 17px;\r\n");
      out.write("  border: 1px solid grey;\r\n");
      out.write("  float: left;\r\n");
      out.write("  width: 80%;\r\n");
      out.write("  background: #f1f1f1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form.example button {\r\n");
      out.write("  float: left;\r\n");
      out.write("  width: 20%;\r\n");
      out.write("  padding: 5px;\r\n");
      out.write("  background: #2196F3;\r\n");
      out.write("  color: white;\r\n");
      out.write("  font-size: 17px;\r\n");
      out.write("  border: 1px solid grey;\r\n");
      out.write("  border-left: none;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form.example button:hover {\r\n");
      out.write("  background: #0b7dda;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form.example::after {\r\n");
      out.write("  content: \"\";\r\n");
      out.write("  clear: both;\r\n");
      out.write("  display: table;\r\n");
      out.write("}\r\n");
      out.write(" .addbutton .card {\r\n");
      out.write("  width:350px;\r\n");
      out.write("  /* background-color:#FCF3CF; */\r\n");
      out.write("} \r\n");
      out.write(" /* .addbutton .card-body {\r\n");
      out.write("  width:350px;\r\n");
      out.write("}  */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <!-- ======= Top Bar ======= -->\r\n");
      out.write(" <!--  <section id=\"topbar\" class=\"d-flex align-items-center\">\r\n");
      out.write("    <div class=\"container d-flex justify-content-center justify-content-md-between\">\r\n");
      out.write("      <div class=\"contact-info d-flex align-items-center\">\r\n");
      out.write("        <i class=\"bi bi-envelope d-flex align-items-center\"><a href=\"mailto:contact@example.com\">contact@example.com</a></i>\r\n");
      out.write("        <i class=\"bi bi-phone d-flex align-items-center ms-4\"><span>+1 5589 55488 55</span></i>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"social-links d-none d-md-flex align-items-center\">\r\n");
      out.write("        <a href=\"#\" class=\"twitter\"><i class=\"bi bi-twitter\"></i></a>\r\n");
      out.write("        <a href=\"#\" class=\"facebook\"><i class=\"bi bi-facebook\"></i></a>\r\n");
      out.write("        <a href=\"#\" class=\"instagram\"><i class=\"bi bi-instagram\"></i></a>\r\n");
      out.write("        <a href=\"#\" class=\"linkedin\"><i class=\"bi bi-linkedin\"></i></i></a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section> -->\r\n");
      out.write("\r\n");
      out.write("  <!-- ======= Header ======= -->\r\n");
      out.write("  <header id=\"header\" class=\"d-flex align-items-center\">\r\n");
      out.write("    <div class=\"container d-flex justify-content-between\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"logo\">\r\n");
      out.write("        <h1 class=\"text-light\"><a href=\"Home.jsp\">AgriTech</a></h1>\r\n");
      out.write("        <!-- Uncomment below if you prefer to use an image logo -->\r\n");
      out.write("        <!-- <a href=\"index.html\"><img src=\"assets/img/logo.png\" alt=\"\" class=\"img-fluid\"></a>-->\r\n");
      out.write("      </div>\r\n");
      out.write("     \r\n");
      out.write("     <form class=\"example\" action=\"/action_page.php\" style=\"margin:auto;max-width:300px\">\r\n");
      out.write("  <input type=\"text\" placeholder=\"Search..\" name=\"search2\">\r\n");
      out.write("  <button type=\"submit\"><i class=\"fa fa-search\"></i></button>\r\n");
      out.write("</form>\r\n");
      out.write("      <nav id=\"navbar\" class=\"navbar\">\r\n");
      out.write("        <ul>\r\n");
      out.write("        <li><a href=\"Home.jsp\"><img src=\"assets/img/IFlag.png\">India</a></li>\r\n");
      out.write("       <!--  <li class=\"dropdown\"><a href=\"#\"><span>All Categories</span> <i class=\"bi bi-chevron-right\"></i></a>\r\n");
      out.write("                <ul>\r\n");
      out.write("                  \r\n");
      out.write("                  <li><a href=\"#\">Vegetables</a></li>\r\n");
      out.write("                  <li><a href=\"#\">Fruits</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </li> -->\r\n");
      out.write("             <!--  <li><a href=\"ProductE-ShopDetails.jsp\"><i class=\"fa fa-shopping-cart\">Cart</i></a></li>  -->\r\n");
      out.write("              <li class=\"dropdown\">\r\n");
      out.write("           <a style=\"color:white;\"><b>Welcome");
response.setContentType("text/html");  
				 HttpSession sessio=request.getSession(true);  
	               if(session!=null){  
	               String firstname=(String)session.getAttribute("firstname");  
	                out.print(" "+firstname+""); }   
      out.write("</b><i class=\"bi bi-chevron-down\"></i></a>\r\n");
      out.write("         <ul> <li><a href=\"LogoutCon\">Logout</a></li> </ul></li>        \r\n");
      out.write("         \r\n");
      out.write("       <!--  <li><a href=\"\">Add Cart</a></li>     -->    \r\n");
      out.write("        </ul>\r\n");
      out.write("        <i class=\"bi bi-list mobile-nav-toggle\"></i>\r\n");
      out.write("      </nav><!-- .navbar -->\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </header><!-- End Header -->\r\n");
      out.write("\r\n");
      out.write("  <!-- ======= Hero Section ======= -->\r\n");
      out.write(" \r\n");
      out.write("  <!--   ======= Services Section ======= -->\r\n");
      out.write("<section id=\"testimonials\" class=\"testimonials\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"testimonials-slider swiper\" data-aos=\"fade-up\" data-aos-delay=\"100\">\r\n");
      out.write("          <div class=\"swiper-wrapper\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"swiper-slide\">\r\n");
      out.write("              <div class=\"testimonial-item\">\r\n");
      out.write("                <img src=\"assets/img/Veg1.jpg\" class=\"testimonial-img\" alt=\"\">\r\n");
      out.write("                <!-- <h3>Saul Goodman</h3>\r\n");
      out.write("                <h4>Ceo &amp; Founder</h4> -->\r\n");
      out.write("                <!-- <p>\r\n");
      out.write("                  <i class=\"bx bxs-quote-alt-left quote-icon-left\"></i>\r\n");
      out.write("                  Proin iaculis purus consequat sem cure digni ssim donec porttitora entum suscipit rhoncus. Accusantium quam, ultricies eget id, aliquam eget nibh et. Maecen aliquam, risus at semper.\r\n");
      out.write("                  <i class=\"bx bxs-quote-alt-right quote-icon-right\"></i>\r\n");
      out.write("                </p> -->\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"swiper-slide\">\r\n");
      out.write("              <div class=\"testimonial-item\">\r\n");
      out.write("                <img src=\"assets/img/veg2.jpg\" class=\"testimonial-img\" alt=\"\">\r\n");
      out.write("                <!-- <h3>Sara Wilsson</h3>\r\n");
      out.write("                <h4>Designer</h4> -->\r\n");
      out.write("               <!--  <p>\r\n");
      out.write("                  <i class=\"bx bxs-quote-alt-left quote-icon-left\"></i>\r\n");
      out.write("                  Export tempor illum tamen malis malis eram quae irure esse labore quem cillum quid cillum eram malis quorum velit fore eram velit sunt aliqua noster fugiat irure amet legam anim culpa.\r\n");
      out.write("                  <i class=\"bx bxs-quote-alt-right quote-icon-right\"></i>\r\n");
      out.write("                </p> -->\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"swiper-slide\">\r\n");
      out.write("              <div class=\"testimonial-item\">\r\n");
      out.write("               \r\n");
      out.write("                <img src=\"assets/img/Veg3.jpg\" class=\"testimonial-img\" alt=\"\">\r\n");
      out.write("                <!-- <h3>Jena Karlis</h3>\r\n");
      out.write("                <h4>Store Owner</h4> -->\r\n");
      out.write("                <!-- <p>\r\n");
      out.write("                  <i class=\"bx bxs-quote-alt-left quote-icon-left\"></i>\r\n");
      out.write("                  Enim nisi quem export duis labore cillum quae magna enim sint quorum nulla quem veniam duis minim tempor labore quem eram duis noster aute amet eram fore quis sint minim.\r\n");
      out.write("                  <i class=\"bx bxs-quote-alt-right quote-icon-right\"></i>\r\n");
      out.write("                </p> -->\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"swiper-slide\">\r\n");
      out.write("              <div class=\"testimonial-item\">\r\n");
      out.write("                <img src=\"assets/img/Veg4.jpg\" class=\"testimonial-img\" alt=\"\">\r\n");
      out.write("                <!-- <h3>Matt Brandon</h3>\r\n");
      out.write("                <h4>Freelancer</h4> -->\r\n");
      out.write("               <!--  <p>\r\n");
      out.write("                  <i class=\"bx bxs-quote-alt-left quote-icon-left\"></i>\r\n");
      out.write("                  Fugiat enim eram quae cillum dolore dolor amet nulla culpa multos export minim fugiat minim velit minim dolor enim duis veniam ipsum anim magna sunt elit fore quem dolore labore illum veniam.\r\n");
      out.write("                  <i class=\"bx bxs-quote-alt-right quote-icon-right\"></i>\r\n");
      out.write("                </p> -->\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"swiper-pagination\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("    \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    \r\n");
      out.write("    <!--  -->\r\n");
      out.write("    \r\n");
      out.write("    <section id=\"pricing\" class=\"pricing\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"section-title\" data-aos=\"zoom-in\">\r\n");
      out.write("        \r\n");
      out.write("          <h3> <span></span></h3>\r\n");
      out.write("          <p></p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("        ");

                try{
                	
                
                	Connection con=DBConnection.getConnection();
                    Statement st=con.createStatement();
                    ResultSet rs=st.executeQuery("select * from addproduct");  
                   /*  ResultSet rs=st.executeQuery("select addcategoryauction.id,addcategoryauction.categoryname,addsubcategoryauction.subcategoryname,addsessiondateauction.date,addsessiontimeauction.time,addcategoryauction.status from addcategoryauction inner join addsubcategoryauction on addcategoryauction.cat=addsubcategoryauction.cat inner join addsessiondateauction on addcategoryauction.cat=addsessiondateauction.cat inner join addsessiontimeauction on addcategoryauction.cat=addsessiontimeauction.cat");
                     */
                    //while(rs.next())
                    	
                    while(rs.next()) {
                   	
      out.write("\r\n");
      out.write("                   	\r\n");
      out.write("                  <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                   	\r\n");
      out.write("            <div class=\"box recommended\" data-aos=\"zoom-in\" data-aos-delay=\"100\">\r\n");
      out.write("              <!-- <span class=\"recommended-badge\"> -->\r\n");
      out.write("                        </button></span>\r\n");
      out.write("                         \r\n");
      out.write("              <h4><td><img alt=\"Profile Pic\" src=\"NewProductPic.jsp?id=");
      out.print(rs.getInt(1) );
      out.write("\"  width=\"150px\" height=\"150px\"/></td>\r\n");
      out.write("                    	 </h4>\r\n");
      out.write("              Name: ");
      out.print(rs.getString(5) );
      out.write("<br>\r\n");
      out.write("              Price: ");
      out.print(rs.getString(8) );
      out.write("<br>             \r\n");
      out.write("              Weight: ");
      out.print(rs.getString(9) );
      out.write("\r\n");
      out.write("              <div class=\"btn-wrap\">\r\n");
      out.write("          \r\n");
      out.write("               <button style=\"background-color:green;\"><a style=\"color:white;\" href=\"ProductE-ShopDetails.jsp?name=");
      out.print(rs.getString(5));
      out.write("\"> Add To Cart</a></button>\r\n");
      out.write("              \r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        \r\n");
      out.write("       \r\n");
      out.write("                   	\r\n");
      out.write("                   	");
 
                   	}
                }catch(Exception e)
                {
                	
                	
                }
                
      out.write("\r\n");
      out.write("\r\n");
      out.write("          \r\n");
      out.write("\r\n");
      out.write("          \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </section><!-- End Pricing Section --> \r\n");
      out.write("      \r\n");
      out.write("  <!-- Vendor JS Files -->\r\n");
      out.write("  <script src=\"assets/vendor/purecounter/purecounter.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/aos/aos.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/glightbox/js/glightbox.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/isotope-layout/isotope.pkgd.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/swiper/swiper-bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/php-email-form/validate.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Template Main JS File -->\r\n");
      out.write("  <script src=\"assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
