/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.56
 * Generated at: 2023-03-20 10:52:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import java.sql.Statement;
import com.connection.DBConnection;
import java.sql.Connection;
import javax.servlet.http.HttpSession;

public final class RetailerHome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("javax.servlet.http.HttpSession");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("com.connection.DBConnection");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("\r\n");
      out.write("  <title>AgriFood</title>\r\n");
      out.write("  <meta content=\"\" name=\"description\">\r\n");
      out.write("  <meta content=\"\" name=\"keywords\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Favicons -->\r\n");
      out.write("  <link href=\"assets/img/favicon.png\" rel=\"icon\">\r\n");
      out.write("  <link href=\"assets/img/apple-touch-icon.png\" rel=\"apple-touch-icon\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Google Fonts -->\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor CSS Files -->\r\n");
      out.write("  <link href=\"assets/vendor/aos/aos.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/vendor/bootstrap-icons/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/vendor/boxicons/css/boxicons.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/vendor/glightbox/css/glightbox.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/vendor/swiper/swiper-bundle.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Template Main CSS File -->\r\n");
      out.write("  <link href=\"assets/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <!-- =======================================================\r\n");
      out.write("  * Template Name: Remember - v4.7.0\r\n");
      out.write("  * Template URL: https://bootstrapmade.com/remember-free-multipurpose-bootstrap-template/\r\n");
      out.write("  * Author: BootstrapMade.com\r\n");
      out.write("  * License: https://bootstrapmade.com/license/\r\n");
      out.write("  ======================================================== -->\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".card {\r\n");
      out.write("    box-shadow: 0 1px 3px 0 rgba(0,0,0,.1), 0 1px 2px 0 rgba(0,0,0,.06);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card {\r\n");
      out.write("   /*  position: relative; */\r\n");
      out.write("   /*  display: flex; */\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    min-width: 0;\r\n");
      out.write("    word-wrap: break-word;\r\n");
      out.write("    background-color: #D7E8E8;\r\n");
      out.write("    background-clip: border-box;\r\n");
      out.write("    border: 0 solid rgba(0,0,0,.125);\r\n");
      out.write("    border-radius: .25rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-body {\r\n");
      out.write("    flex: 1 1 auto;\r\n");
      out.write("    min-height: 1px;\r\n");
      out.write("    padding: 1rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".gutters-sm {\r\n");
      out.write("    margin-right: -8px;\r\n");
      out.write("    margin-left: -8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".gutters-sm>.col, .gutters-sm>[class*=col-] {\r\n");
      out.write("    padding-right: 8px;\r\n");
      out.write("    padding-left: 8px;\r\n");
      out.write("}\r\n");
      out.write(".mb-3, .my-3 {\r\n");
      out.write("    margin-bottom: 1rem!important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bg-gray-300 {\r\n");
      out.write("    background-color: #e2e8f0;\r\n");
      out.write("}\r\n");
      out.write(".h-100 {\r\n");
      out.write("    height: 100%!important;\r\n");
      out.write("}\r\n");
      out.write(".shadow-none {\r\n");
      out.write("    box-shadow: none!important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#services .btn {\r\n");
      out.write("  font-family: \"Raleway\", sans-serif;\r\n");
      out.write("  font-weight: 500;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  letter-spacing: 1px;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  padding: 8px 28px;\r\n");
      out.write("  border-radius: 50px;\r\n");
      out.write("  transition: 0.5s;\r\n");
      out.write("  margin: 10px;\r\n");
      out.write("  border: 2px solid #8fc04e;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("}\r\n");
      out.write(".services .services-btn {\r\n");
      out.write("  font-family: \"Raleway\", sans-serif;\r\n");
      out.write("  font-weight: 600;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  letter-spacing: 1px;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  padding: 8px 28px;\r\n");
      out.write("  border-radius: 25px;\r\n");
      out.write("  transition: 0.5s;\r\n");
      out.write("  margin-top: 10px;\r\n");
      out.write("  border: 2px solid #fff;\r\n");
      out.write("  background-color:#0B7E51;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("}\r\n");
      out.write("/* input[type=text], input[type=password], input[type=date],input[id=select]{\r\n");
      out.write("  \r\n");
      out.write("  width: 90%;\r\n");
      out.write("  padding: 2px 2px;\r\n");
      out.write("  margin: 2px 0;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  border: 1px solid #ccc;\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("  align:center;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <!-- ======= Header ======= -->\r\n");
      out.write("  <header id=\"header\" class=\"d-flex align-items-center\">\r\n");
      out.write("    <div class=\"container d-flex justify-content-between\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"logo\">\r\n");
      out.write("        <h1 class=\"text-light\"><a href=\"Home.jsp\">AgriFood</a></h1>\r\n");
      out.write("        <!-- Uncomment below if you prefer to use an image logo -->\r\n");
      out.write("        <!-- <a href=\"index.html\"><img src=\"assets/img/logo.png\" alt=\"\" class=\"img-fluid\"></a>-->\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("      <nav id=\"navbar\" class=\"navbar\">\r\n");
      out.write("      <ul>\r\n");
      out.write("        <!-- <li><a href=\"Home.jsp\"><img src=\"assets/img/IFlag.png\">India</a></li> -->        \r\n");
      out.write("          <li><a href=\"MyProfile.jsp\">My Profile</a></li>   \r\n");
      out.write("          <!-- <li><a href=\"\">Live Trading</a></li>        \r\n");
      out.write("          <li><a href=\"\">Mandi Rates</a></li>\r\n");
      out.write("          <li><a href=\"GovernmentScheme.jsp\">Government Scheme</a></li> -->\r\n");
      out.write("          <li><a href=\"E-Market.jsp\">E-Market</a></li>\r\n");
      out.write("        \r\n");
      out.write("          <!-- <li class=\"dropdown\"><a href=\"#\"><span>Complaint</span> <i class=\"bi bi-chevron-down\"></i></a>\r\n");
      out.write("            <ul>       \r\n");
      out.write("              <li><a href=\"AddComplaint.jsp\">Add Complaint</a></li>\r\n");
      out.write("              \r\n");
      out.write("            </ul> -->\r\n");
      out.write("          </li>\r\n");
      out.write("         <!--  <li><a href=\"CreateNewOrder.jsp\">Create New Order</a></li> -->\r\n");
      out.write("          <li><a href=\"\">View Feedback</a></li>\r\n");
      out.write("          <li class=\"dropdown\"><a href=\"#\"><span>Welcome");
response.setContentType("text/html");  
				 HttpSession sessio=request.getSession(true);  
	               if(session!=null){  
	               String firstname=(String)session.getAttribute("firstname");  
	                out.print(" "+firstname+""); }   
      out.write("</span> <i class=\"bi bi-chevron-down\"></i></a>\r\n");
      out.write("               <ul>\r\n");
      out.write("	                <li><a href=\"LogoutCon\">Logout</a></li>\r\n");
      out.write("	                </ul>\r\n");
      out.write("          </ul>\r\n");
      out.write("          <!-- <ul style=\"text-align:right\">\r\n");
      out.write("				\r\n");
      out.write("				</ul> -->\r\n");
      out.write("          \r\n");
      out.write("        <i class=\"bi bi-list mobile-nav-toggle\"></i>\r\n");
      out.write("      </nav><!-- .navbar -->\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </header>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write(" <!--   ======= Services Section ======= -->   \r\n");
      out.write("    <section id=\"services\" class=\"services\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <!-- <div class=\"row justify-content-between\"> -->\r\n");
      out.write("         \r\n");
      out.write("                  \r\n");
      out.write("         <div class=\"col-lg-6\">\r\n");
      out.write("        <img alt=\"\" src=\"assets/img/retailer.jpg\" height=\"450px\" width=\"500px\">\r\n");
      out.write("          \r\n");
      out.write("            <!-- </div> -->\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-lg-6\">\r\n");
      out.write("        <div class=\"text-center\">\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-info btn-lg\" style=\"height:40px; width:250px; background-color:black;\"><a href=\"SendBatchRetailer.jsp\" style=\"color:white;\">Received Batch</a></button><br>\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-info btn-lg\" style=\"height:40px; width:250px; background-color:black;\"><a href=\"ViewRawMaterial1.jsp\" style=\"color:white;\">Buy Material From Farmer</a></button><br>\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-info btn-lg\" style=\"height:40px; width:250px; background-color:black;\"><a href=\"ViewRawMaterial2.jsp\" style=\"color:white;\">View Buy Raw Material</a></button><br>\r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("           <button type=\"button\" class=\"btn btn-info btn-lg\" style=\"height:40px; width:250px; background-color:black;\" data-toggle=\"modal\" data-target=\"#myModal\">Add Category</button><br>\r\n");
      out.write("          \r\n");
      out.write("           <button type=\"button\" class=\"btn btn-info btn-lg\" style=\"height:40px; width:250px; background-color:black;\"><a href=\"ViewCategory.jsp\" style=\"color:white;\">View Category</a></button><br>\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-info btn-lg\" style=\"height:40px; width:250px; background-color:black;\" data-toggle=\"modal\" data-target=\"#myModal1\">Add Sub-Category</button><br>\r\n");
      out.write("          \r\n");
      out.write("          <button type=\"button\" class=\"btn btn-info btn-lg\" style=\"height:40px; width:250px; background-color:black;\"><a href=\"ViewSubCat.jsp\" style=\"color:white;\">View Sub-Category</a></button><br>\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-info btn-lg\" style=\"height:40px; width:250px; background-color:black;\" data-toggle=\"modal\" data-target=\"#myModal2\">Add Product</button><br>\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-info btn-lg\" style=\"height:40px; width:250px; background-color:black;\"><a href=\"ViewProductRetailer.jsp\" style=\"color:white;\">View Product</a></button><br>\r\n");
      out.write("                                                                                                                               \r\n");
      out.write("        </div></div></div>\r\n");
      out.write("     \r\n");
      out.write("        \r\n");
      out.write("        <!---------------------------------------Add Category---------------------------------------> \r\n");
      out.write(" <div class=\"container\">\r\n");
      out.write(" \r\n");
      out.write(" <!--  <button type=\"button\" class=\"btn btn-info btn-lg\" data-toggle=\"modal\" data-target=\"#myModal\">Open Modal</button> -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Modal -->\r\n");
      out.write("  <div class=\"modal fade\" id=\"myModal\" role=\"dialog\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("    \r\n");
      out.write("      <!-- Modal content-->\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("         \r\n");
      out.write("          <h4 class=\"modal-title\">Add Category</h4>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-body\">\r\n");
      out.write("    \r\n");
      out.write("              <form action=\"AddCategoryCon\" method=\"post\">\r\n");
      out.write("            \r\n");
      out.write("              <div class=\"form-group mt-1\">\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" name=\"categoryname\" id=\"categoryname\" placeholder=\"Enter Category Name\" required>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group mt-1\">\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" name=\"mobileno\" id=\"mobileno\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mobileno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\r\n");
      out.write("              </div>\r\n");
      out.write("                  <div class=\"text-center\">        \r\n");
      out.write("              <input type=\"Submit\" class=\"services-btn\" value=\"Add Category\"><br>\r\n");
      out.write("                  </div>                 \r\n");
      out.write("              </form>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"modal-footer\">\r\n");
      out.write("          <button type=\"button\" class=\"btn\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("</div>\r\n");
      out.write("      \r\n");
      out.write("          \r\n");
      out.write("        \r\n");
      out.write("        <!---------------------------------------Add Sub-Category---------------------------------------> \r\n");
      out.write(" <div class=\"container\">\r\n");
      out.write(" \r\n");
      out.write("   \r\n");
      out.write("  <!-- Modal -->\r\n");
      out.write("  <div class=\"modal fade\" id=\"myModal1\" role=\"dialog\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("    \r\n");
      out.write("      <!-- Modal content-->\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("         \r\n");
      out.write("          <h4 class=\"modal-title\">Add Sub-Category</h4>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-body\">\r\n");
      out.write("    \r\n");
      out.write("             <form action=\"AddSubCatCon\" method=\"post\" align=\"center\">\r\n");
      out.write("              \r\n");
      out.write("                <div class=\"form-group mt-1\">\r\n");
      out.write("            \r\n");
      out.write("            <select id=\"categoryname\" name=\"categoryname\" class=\"form-group mt-1\">\r\n");
      out.write("            <option>Select Category</option>\r\n");
      out.write("\r\n");
      out.write("                ");

                try{
                	
                
                	Connection con=DBConnection.getConnection();
                    Statement st=con.createStatement();
                    ResultSet rs=st.executeQuery("select * from addcategory"); 
                  //while(rs.next())
                    while(rs.next()) {
                   	
      out.write("\r\n");
      out.write("                   	<option>");
      out.print(rs.getString("categoryname"));
      out.write("</option>\r\n");
      out.write("                   	");
 
                   	}
                }catch(Exception e)
                {
                	
                	
                }
                
      out.write("\r\n");
      out.write("                </select>  </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"form-group mt-1\">\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" name=\"subcatname\" id=\"subcatname\" placeholder=\"Enter Sub-Category Name\" required>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group mt-1\">\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" name=\"mobileno\" id=\"mobileno\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mobileno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\r\n");
      out.write("              </div>   \r\n");
      out.write("              \r\n");
      out.write("               <div class=\"form-group mt-1\" align=\"center\">                        \r\n");
      out.write("                             \r\n");
      out.write("        <input type=\"Submit\" class=\"services-btn\" value=\"Add Sub-Category\"><br>\r\n");
      out.write("        \r\n");
      out.write("  </div></form>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"modal-footer\">\r\n");
      out.write("          <button type=\"button\" class=\"btn\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("     <!---------------------------------------Add Product---------------------------------------> \r\n");
      out.write(" <div class=\"container\">\r\n");
      out.write(" \r\n");
      out.write(" <!--  <button type=\"button\" class=\"btn btn-info btn-lg\" data-toggle=\"modal\" data-target=\"#myModal\">Open Modal</button> -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Modal -->\r\n");
      out.write("  <div class=\"modal fade\" id=\"myModal2\" role=\"dialog\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("    \r\n");
      out.write("      <!-- Modal content-->\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("          \r\n");
      out.write("          <h4 class=\"modal-title\">Add Product</h4>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-body\">\r\n");
      out.write("    \r\n");
      out.write("              <form action=\"AddProductCon\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("              \r\n");
      out.write("               <div class=\"form-group mt-1\">\r\n");
      out.write("           \r\n");
      out.write("                <select id=\"SelectCategory\" name=\"SelectCategory\" class=\"form-group mt-1\">\r\n");
      out.write("            <option>Select Category</option>\r\n");
      out.write("\r\n");
      out.write("                ");

                try{
                	
                
                	Connection con=DBConnection.getConnection();
                    Statement st=con.createStatement();
                    ResultSet rs=st.executeQuery("select * from addcategory"); 
                  //while(rs.next())
                    while(rs.next()) {
                   	
      out.write("\r\n");
      out.write("                   	<option>");
      out.print(rs.getString("categoryname"));
      out.write("</option>\r\n");
      out.write("                   	");
 
                   	}
                }catch(Exception e)
                {
                	
                	
                }
                
      out.write("\r\n");
      out.write("                </select>  </div>\r\n");
      out.write("                <div class=\"form-group mt-1\">\r\n");
      out.write("              <input type=\"file\" name=\"file\" class=\"form-control custom-labels\" /> \r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"form-group mt-1\">\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" name=\"name\" id=\"name\" placeholder=\"Product Name\" required>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group mt-1\">\r\n");
      out.write("              <label>Manufacturing Date</label>\r\n");
      out.write("                <input type=\"date\" class=\"form-control\" name=\"manudate\" id=\"manudate\" placeholder=\"Manufacturing date\" required>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group mt-1\">\r\n");
      out.write("              <label>Exp Date</label>\r\n");
      out.write("                <input type=\"date\" class=\"form-control\" name=\"expdate\" id=\"expdate\" placeholder=\"Expiry Name\" required>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group mt-1\">\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" name=\"price\" id=\"price\" placeholder=\"Price\" required>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group mt-1\">\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" name=\"weight\" id=\"weight\" placeholder=\"weight\" required>\r\n");
      out.write("              </div>\r\n");
      out.write("              \r\n");
      out.write("               \r\n");
      out.write("               \r\n");
      out.write("               \r\n");
      out.write("              ");
      out.write(" \r\n");
      out.write("                  <div class=\"text-center\">        \r\n");
      out.write("              <input type=\"Submit\" class=\"services-btn\" value=\"Add Product\"><br>\r\n");
      out.write("                  </div>                 \r\n");
      out.write("              </form>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"modal-footer\">\r\n");
      out.write("          <button type=\"button\" class=\"btn\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("</div>\r\n");
      out.write("       </section> \r\n");
      out.write("          \r\n");
      out.write("<!---------------------------------------END Add Catagory---------------------------------------> \r\n");
      out.write("         \r\n");
      out.write("  <!-- Vendor JS Files -->\r\n");
      out.write("  <script src=\"assets/vendor/purecounter/purecounter.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/aos/aos.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/glightbox/js/glightbox.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/isotope-layout/isotope.pkgd.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/swiper/swiper-bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/php-email-form/validate.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Template Main JS File -->\r\n");
      out.write("  <script src=\"assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
